---
title: "EDS 223: Week 2"
format: html
editor_options: 
  chunk_output_type: console
---


```{r}
rm(list = ls())
library(sf)
library(tidyverse)
library(spData)
library(tmap)
```

```{r}
london_point <- st_point(c(0.1, 51.5))

london_geom <- st_sfc(london_point, crs = 4326)

london_attrib <- data.frame(
  name = "London", 
  temperature = 25, 
  date = as.Date("2017-06-21")
)

london_sf <- st_sf(london_attrib, geometry = london_geom)

class(london_sf)

st_crs(london_sf)$IsGeographic
```

```{r}
world <- spData::world
  
names(world)

summary(world$lifeExp)
```

```{r}
world_df <- world |> 
  select(-geom)

world_df <- world |> 
  select(continent)

colnames(world_df)
```

```{r}
world_df <- st_drop_geometry(world)
class(world_df)
```

## Reprojecting data

```{r}
london_proj <- data.frame(x = 53000, y = 180000) |> 
  st_as_sf(coords = c("x", "y"), crs = "EPSG:27700")

st_crs(london_proj) == st_crs(london_sf)

london_sf_transform <-st_transform(london_sf, crs = st_crs(london_proj))
```

```{r}
if(st_crs(london_sf_transform)== st_crs(london_proj)){
  print("coordinate reference systms of datasets match")
} else{
  error("coordinate refrence systems do not match")
}
```

```{r}
tm_shape(world, projection = 8857) +
  tm_fill(col = "area_km2")

```

```{r}
tm_shape(world, projection = 3395) +
  tm_fill (col = "area_km2")
```

## Vector attribute subsetting

```{r}
world |> 
  select(name_long, pop)

world |> 
  select(-subregion)

world |> 
  select(name = name_long, population = pop)
```

```{r}
world1 <- world |> 
  filter(area_km2 <10000)
```

```{r}
world |> 
  filter(continent == "Asia") |> 
  select(name_long, continent, lifeExp) |> 
  slice_max(lifeExp) |> 
  st_drop_geometry()
```

```{r}
world |> 
  group_by(continent) |> 
  summarise(population = sum(pop, na.rm = TRUE)) |> 
  st_drop_geometry()
```

# Joins with vector attributes

```{r}
coffee_data <- spData::coffee_data

nrow(coffee_data)
nrow(world)
```

```{r}
world_coffee <- left_join(world, coffee_data, by = "name_long")
world_coffee
```

